BEGIN;

/* Migration 010 / P1B-1: canonical attendance shadow storage only. */
DO $precondition$
DECLARE
  v_name text;
BEGIN
  IF session_user <> 'postgres' THEN
    RAISE EXCEPTION 'MIGRATION_10_PRECONDITION: run as postgres';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'public')
     OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon')
     OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    RAISE EXCEPTION 'MIGRATION_10_PRECONDITION: required schema or roles are missing';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_timezone_names
    WHERE name = 'Australia/Melbourne'
  ) THEN
    RAISE EXCEPTION 'MIGRATION_10_PRECONDITION: Australia/Melbourne timezone is unavailable';
  END IF;

  IF pg_catalog.format_type((SELECT atttypid FROM pg_catalog.pg_attribute
      WHERE attrelid = 'public.profiles'::regclass AND attname = 'id' AND NOT attisdropped), NULL) IS DISTINCT FROM 'uuid'
     OR pg_catalog.format_type((SELECT atttypid FROM pg_catalog.pg_attribute
      WHERE attrelid = 'public.shifts'::regclass AND attname = 'id' AND NOT attisdropped), NULL) IS DISTINCT FROM 'bigint'
     OR pg_catalog.format_type((SELECT atttypid FROM pg_catalog.pg_attribute
      WHERE attrelid = 'public.time_clock'::regclass AND attname = 'id' AND NOT attisdropped), NULL) IS DISTINCT FROM 'bigint'
     OR pg_catalog.format_type((SELECT atttypid FROM pg_catalog.pg_attribute
      WHERE attrelid = 'public.time_clock'::regclass AND attname = 'staff_id' AND NOT attisdropped), NULL) IS DISTINCT FROM 'uuid' THEN
    RAISE EXCEPTION 'MIGRATION_10_PRECONDITION: verified legacy column types have drifted';
  END IF;

  FOREACH v_name IN ARRAY ARRAY[
    'payroll_periods', 'work_periods', 'work_period_versions', 'work_period_anomalies',
    'payroll_periods_id_seq', 'work_periods_id_seq',
    'work_period_versions_id_seq', 'work_period_anomalies_id_seq'
  ] LOOP
    IF pg_catalog.to_regclass('public.' || v_name) IS NOT NULL
       OR EXISTS (
         SELECT 1 FROM pg_catalog.pg_type AS t
         JOIN pg_catalog.pg_namespace AS n ON n.oid = t.typnamespace
         WHERE n.nspname = 'public' AND t.typname = v_name
       ) THEN
      RAISE EXCEPTION 'MIGRATION_10_PRECONDITION: conflicting object public.% exists', v_name;
    END IF;
  END LOOP;
END
$precondition$;

CREATE TABLE public.payroll_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  store_id text NOT NULL,
  week_start date NOT NULL,
  week_end date NOT NULL,
  timezone text NOT NULL DEFAULT 'Australia/Melbourne',
  shadow_status text NOT NULL DEFAULT 'BUILDING',
  generation_version integer NOT NULL DEFAULT 1,
  last_refreshed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payroll_periods_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_periods_store_week_key UNIQUE (store_id, week_start),
  CONSTRAINT payroll_periods_week_range_check CHECK (week_end = week_start + 6),
  CONSTRAINT payroll_periods_thursday_check CHECK (EXTRACT(DOW FROM week_start) = 4),
  CONSTRAINT payroll_periods_timezone_check CHECK (timezone = 'Australia/Melbourne'),
  CONSTRAINT payroll_periods_shadow_status_check CHECK (
    shadow_status IN ('BUILDING', 'READY_FOR_COMPARISON', 'ERROR')
  ),
  CONSTRAINT payroll_periods_generation_version_check CHECK (generation_version > 0)
);

CREATE TABLE public.work_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  store_id text NOT NULL,
  staff_id uuid NOT NULL,
  payroll_period_id bigint NOT NULL,
  source_type text NOT NULL,
  time_clock_id bigint NULL,
  matched_shift_id bigint NULL,
  status text NOT NULL DEFAULT 'NEEDS_REVIEW',
  current_version_id bigint NULL,
  created_by uuid NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_periods_pkey PRIMARY KEY (id),
  CONSTRAINT work_periods_staff_fk FOREIGN KEY (staff_id)
    REFERENCES public.profiles(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_periods_payroll_period_fk FOREIGN KEY (payroll_period_id)
    REFERENCES public.payroll_periods(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_periods_time_clock_fk FOREIGN KEY (time_clock_id)
    REFERENCES public.time_clock(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_periods_matched_shift_fk FOREIGN KEY (matched_shift_id)
    REFERENCES public.shifts(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_periods_created_by_fk FOREIGN KEY (created_by)
    REFERENCES public.profiles(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_periods_source_type_check CHECK (source_type IN ('CLOCK', 'MANUAL_NO_CLOCK')),
  CONSTRAINT work_periods_status_check CHECK (status IN ('NEEDS_REVIEW', 'READY', 'VOIDED')),
  CONSTRAINT work_periods_source_consistency_check CHECK (
    (source_type = 'CLOCK' AND time_clock_id IS NOT NULL)
    OR
    (source_type = 'MANUAL_NO_CLOCK' AND time_clock_id IS NULL AND created_by IS NOT NULL)
  )
);

CREATE UNIQUE INDEX work_periods_time_clock_unique
  ON public.work_periods (time_clock_id) WHERE time_clock_id IS NOT NULL;
CREATE INDEX work_periods_period_status_idx
  ON public.work_periods (payroll_period_id, status);
CREATE INDEX work_periods_staff_period_idx
  ON public.work_periods (staff_id, payroll_period_id);
CREATE INDEX work_periods_matched_shift_idx
  ON public.work_periods (matched_shift_id) WHERE matched_shift_id IS NOT NULL;

CREATE TABLE public.work_period_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  work_period_id bigint NOT NULL,
  version_number integer NOT NULL,
  disposition text NOT NULL DEFAULT 'ACTIVE',
  matched_shift_id bigint NULL,
  actual_start_at timestamptz NULL,
  actual_end_at timestamptz NULL,
  payable_start_at timestamptz NULL,
  payable_end_at timestamptz NULL,
  reason_code text NOT NULL,
  reason_note text NULL,
  change_source text NOT NULL,
  created_by uuid NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_period_versions_pkey PRIMARY KEY (id),
  CONSTRAINT work_period_versions_period_version_key UNIQUE (work_period_id, version_number),
  CONSTRAINT work_period_versions_id_period_key UNIQUE (id, work_period_id),
  CONSTRAINT work_period_versions_work_period_fk FOREIGN KEY (work_period_id)
    REFERENCES public.work_periods(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_versions_matched_shift_fk FOREIGN KEY (matched_shift_id)
    REFERENCES public.shifts(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_versions_created_by_fk FOREIGN KEY (created_by)
    REFERENCES public.profiles(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_versions_number_check CHECK (version_number > 0),
  CONSTRAINT work_period_versions_disposition_check CHECK (disposition IN ('ACTIVE', 'VOIDED')),
  CONSTRAINT work_period_versions_change_source_check CHECK (
    change_source IN ('SYSTEM', 'MANAGER', 'OWNER', 'LEGACY_IMPORT')
  ),
  CONSTRAINT work_period_versions_actual_range_check CHECK (
    actual_start_at IS NULL OR actual_end_at IS NULL OR actual_end_at > actual_start_at
  ),
  CONSTRAINT work_period_versions_payable_range_check CHECK (
    payable_start_at IS NULL OR payable_end_at IS NULL OR payable_end_at > payable_start_at
  ),
  CONSTRAINT work_period_versions_reason_code_check CHECK (btrim(reason_code) <> ''),
  CONSTRAINT work_period_versions_other_note_check CHECK (
    reason_code <> 'OTHER' OR (reason_note IS NOT NULL AND btrim(reason_note) <> '')
  ),
  CONSTRAINT work_period_versions_actor_check CHECK (
    change_source NOT IN ('MANAGER', 'OWNER') OR created_by IS NOT NULL
  )
);

ALTER TABLE public.work_periods
  ADD CONSTRAINT work_periods_current_version_same_period_fk
  FOREIGN KEY (current_version_id, id)
  REFERENCES public.work_period_versions(id, work_period_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE public.work_period_anomalies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  work_period_id bigint NOT NULL,
  anomaly_type text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  detected_at timestamptz NOT NULL DEFAULT now(),
  resolved_by uuid NULL,
  resolved_at timestamptz NULL,
  resolution_reason_code text NULL,
  resolution_note text NULL,
  resolution_version_id bigint NULL,
  CONSTRAINT work_period_anomalies_pkey PRIMARY KEY (id),
  CONSTRAINT work_period_anomalies_work_period_fk FOREIGN KEY (work_period_id)
    REFERENCES public.work_periods(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_anomalies_resolved_by_fk FOREIGN KEY (resolved_by)
    REFERENCES public.profiles(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_anomalies_resolution_same_period_fk
    FOREIGN KEY (resolution_version_id, work_period_id)
    REFERENCES public.work_period_versions(id, work_period_id)
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT work_period_anomalies_type_check CHECK (anomaly_type IN (
    'MISSING_CLOCK_IN', 'MISSING_CLOCK_OUT', 'EARLY_START', 'LATE_START',
    'EARLY_FINISH', 'LATE_FINISH', 'UNROSTERED_WORK', 'AMBIGUOUS_MATCH',
    'OVERLAPPING_CLOCK', 'DUPLICATE_CLOCK', 'MISSED_CLOCK_OUT',
    'INVALID_CLOCK_RANGE', 'CROSSES_MIDNIGHT', 'SHIFT_STAFF_MISMATCH',
    'SOURCE_CHANGED_AFTER_REVIEW'
  )),
  CONSTRAINT work_period_anomalies_severity_check CHECK (severity IN ('WARNING', 'BLOCKING')),
  CONSTRAINT work_period_anomalies_status_check CHECK (status IN ('OPEN', 'RESOLVED', 'DISMISSED')),
  CONSTRAINT work_period_anomalies_details_check CHECK (jsonb_typeof(details) = 'object'),
  CONSTRAINT work_period_anomalies_other_note_check CHECK (
    resolution_reason_code IS DISTINCT FROM 'OTHER'
    OR (resolution_note IS NOT NULL AND btrim(resolution_note) <> '')
  )
);

CREATE UNIQUE INDEX work_period_anomalies_open_type_unique
  ON public.work_period_anomalies (work_period_id, anomaly_type)
  WHERE status = 'OPEN';
CREATE INDEX work_period_anomalies_status_severity_period_idx
  ON public.work_period_anomalies (status, severity, work_period_id);
CREATE INDEX work_period_anomalies_type_idx
  ON public.work_period_anomalies (anomaly_type);

ALTER TABLE public.payroll_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_period_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_period_anomalies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Active Manager/Owner can read payroll periods"
  ON public.payroll_periods AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles AS p
    WHERE p.id = auth.uid() AND p.is_active IS TRUE
      AND upper(p.role::text) IN ('MANAGER', 'OWNER')
  ));
CREATE POLICY "Active Manager/Owner can read work periods"
  ON public.work_periods AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles AS p
    WHERE p.id = auth.uid() AND p.is_active IS TRUE
      AND upper(p.role::text) IN ('MANAGER', 'OWNER')
  ));
CREATE POLICY "Active Manager/Owner can read work period versions"
  ON public.work_period_versions AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles AS p
    WHERE p.id = auth.uid() AND p.is_active IS TRUE
      AND upper(p.role::text) IN ('MANAGER', 'OWNER')
  ));
CREATE POLICY "Active Manager/Owner can read work period anomalies"
  ON public.work_period_anomalies AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles AS p
    WHERE p.id = auth.uid() AND p.is_active IS TRUE
      AND upper(p.role::text) IN ('MANAGER', 'OWNER')
  ));

REVOKE ALL ON TABLE public.payroll_periods, public.work_periods,
  public.work_period_versions, public.work_period_anomalies
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.payroll_periods, public.work_periods,
  public.work_period_versions, public.work_period_anomalies TO authenticated;

REVOKE ALL ON SEQUENCE public.payroll_periods_id_seq,
  public.work_periods_id_seq, public.work_period_versions_id_seq,
  public.work_period_anomalies_id_seq FROM PUBLIC, anon, authenticated;

DO $postcondition$
DECLARE
  v_table text;
  v_policy text;
  v_sequence text;
BEGIN
  IF (SELECT count(*) FROM pg_catalog.pg_class AS c
      JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public' AND c.relkind = 'r'
        AND c.relname IN ('payroll_periods','work_periods','work_period_versions','work_period_anomalies')) <> 4 THEN
    RAISE EXCEPTION 'MIGRATION_10_POSTCONDITION: expected four canonical tables';
  END IF;

  FOR v_table, v_policy IN SELECT * FROM (VALUES
    ('payroll_periods', 'Active Manager/Owner can read payroll periods'),
    ('work_periods', 'Active Manager/Owner can read work periods'),
    ('work_period_versions', 'Active Manager/Owner can read work period versions'),
    ('work_period_anomalies', 'Active Manager/Owner can read work period anomalies')
  ) AS x(table_name, policy_name)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_class AS c
      JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public' AND c.relname = v_table
        AND c.relrowsecurity AND NOT c.relforcerowsecurity
    ) OR NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_policies AS p
      WHERE p.schemaname = 'public' AND p.tablename = v_table
        AND p.policyname = v_policy AND p.cmd = 'SELECT'
        AND p.roles = ARRAY['authenticated']::name[]
    ) THEN
      RAISE EXCEPTION 'MIGRATION_10_POSTCONDITION: RLS contract failed for %', v_table;
    END IF;

    IF NOT pg_catalog.has_table_privilege('authenticated', 'public.' || v_table, 'SELECT')
       OR pg_catalog.has_table_privilege('authenticated', 'public.' || v_table, 'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
       OR pg_catalog.has_table_privilege('anon', 'public.' || v_table, 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') THEN
      RAISE EXCEPTION 'MIGRATION_10_POSTCONDITION: table ACL failed for %', v_table;
    END IF;
  END LOOP;

  FOREACH v_sequence IN ARRAY ARRAY[
    'payroll_periods_id_seq', 'work_periods_id_seq',
    'work_period_versions_id_seq', 'work_period_anomalies_id_seq'
  ] LOOP
    IF pg_catalog.to_regclass('public.' || v_sequence) IS NULL
       OR pg_catalog.has_sequence_privilege('authenticated', 'public.' || v_sequence, 'USAGE,SELECT,UPDATE')
       OR pg_catalog.has_sequence_privilege('anon', 'public.' || v_sequence, 'USAGE,SELECT,UPDATE') THEN
      RAISE EXCEPTION 'MIGRATION_10_POSTCONDITION: sequence ACL failed for %', v_sequence;
    END IF;
  END LOOP;

  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint WHERE conname = 'work_periods_current_version_same_period_fk')
     OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint WHERE conname = 'work_period_anomalies_resolution_same_period_fk')
     OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_indexes WHERE schemaname='public' AND indexname='work_periods_time_clock_unique')
     OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_indexes WHERE schemaname='public' AND indexname='work_period_anomalies_open_type_unique') THEN
    RAISE EXCEPTION 'MIGRATION_10_POSTCONDITION: required integrity objects are missing';
  END IF;
END
$postcondition$;

COMMIT;
